### ISSUE TITLE
why the project in inactive mode

### ISSUE THREAD

**Issue by hbakhtiyor** [gitterHQ/request-http-cache#6]
hi there,

do you recommend to use the project in prod? or another caching modules for request.js?

cheers!

**Comment by suprememoocow** [comment]
Hi @hbakhtiyor,

I'm not sure of any other caching modules but I haven't really looked. I wrote this for [Gitter](https://gitter.im) and it's used in production for all communications between Gitter and the GitHub API. It handled about 6.39M requests in the last week (this would actually be much higher, but we have multiple levels of caching of which this is the bottom-most-level)

Does this help?

**Comment by hbakhtiyor** [comment]
hi @suprememoocow,

thanks for your reply, can you please talk a bit about your multiple levels of caching?

**Comment by suprememoocow** [comment]
Starting from the client-side down towards GitHub, we use:
- Client-side caching / etags for some requests, mostly requests where we mirror GitHub APIs directly but replace our user's OAuth token with the GitHub token we store for that user.
- Since we use GitHub as an authorisation mechanism for allowing/denying access to rooms, we will store the outcome of some authorisation calls directly on the request. Technically this isn't really a 'cache' but it serves the same purpose.
- At a lower level we wrap many of our internal APIs in another non-http caching mechansim, built on top of [this module](https://github.com/troupe/snappy-cache). This cache only stores the data that we need from GitHub, not the entire HTTP response + headers, as `request-http-cache` does. This makes it much faster. However, since it has no concept of HTTP caching semantics, this cache is fairly short-lived, as we don't want to serve up stale data. When calling slower GitHub APIs (eg contributors), we 'race' our own cache against the GitHub API call (obviously giving GitHub a head-start) and serve up stale data if we don't receive a response within a timeout period. When we do receive the response, we'll update the cache, ready for the next request for the same data.
- At the bottom of the stack, we use this module with [tentacles](https://github.com/gitterHQ/tentacles), our GitHub API client, as a final level of caching. Our hit rate is between 40% and 50% on average. Because of the higher-level caches, most of the cache hits that we get at this level will still perform an HTTP conditional request, and receive an HTTP 304 response (which doesn't count towards our GitHub rate limits)
- Another advantage of using this cache, is that we'll serve up stale cached content when we get 502 errors from GitHub, for example during a DDOS or an outage. This means that in general, many functions on Gitter will continue to work when the GitHub API isn't available.

**Comment by hbakhtiyor** [comment]
@suprememoocow thanks a lot for your great explanation!
btw, which stacks do you guys use at gitter? meteor? ...

**Comment by suprememoocow** [comment]
@hbakhtiyor I've updated StackShare with our current stack, here http://stackshare.io/gitter/gitter

**Comment by hbakhtiyor** [comment]
thanks, i heard that your scaling better than slack
